# Generated by Django 4.1.2 on 2023-02-18 11:32

import authenticate.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userId",
                    models.CharField(
                        default=authenticate.models.unique_id, max_length=10
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("modifiedAt", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("mobile", models.CharField(default="", max_length=13)),
                ("email", models.EmailField(default="", max_length=30)),
            ],
        ),
    ]
