# Generated by Django 4.1.2 on 2023-02-18 11:32

from django.db import migrations, models
import note.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "noteId",
                    models.CharField(
                        default=note.models.unique_id, editable=False, max_length=30
                    ),
                ),
                ("userId", models.CharField(max_length=10)),
                ("note", models.CharField(max_length=120)),
                ("noteType", models.IntegerField()),
                ("replyTo", models.CharField(default="", max_length=30)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
                ("noteId", models.CharField(max_length=30)),
            ],
        ),
    ]
