# Generated by Django 4.1.2 on 2023-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="image",
            field=models.TextField(blank=True),
        ),
    ]
