# Generated by Django 4.1.2 on 2023-02-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0002_alter_note_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="note",
            field=models.TextField(max_length=120),
        ),
    ]
