# Generated by Django 4.1.2 on 2023-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0003_alter_note_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
                ("noteId", models.CharField(max_length=30)),
                ("userId", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
                ("userId", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ViewerToNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
                ("noteId", models.CharField(max_length=30)),
                ("userId", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="image",
            new_name="attachment",
        ),
        migrations.AddField(
            model_name="note",
            name="attachmentType",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="replyTo",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
